const DATA_MOCK = [
  {
    id: 1,
    first: 'Faun',
    last: 'Lewens',
    email: 'flewens0@japanpost.jp',
  },
  {
    id: 2,
    first: 'Fedora',
    last: 'Jonuzi',
    email: 'fjonuzi1@google.ca',
  },
  {
    id: 3,
    first: 'Domeniga',
    last: 'Helleckas',
    email: 'dhelleckas2@ucoz.com',
  },
  {
    id: 4,
    first: 'Pat',
    last: 'Wilkie',
    email: 'pwilkie3@slate.com',
  },
  {
    id: 5,
    first: 'Dunc',
    last: 'Kuhnel',
    email: 'dkuhnel4@cam.ac.uk',
  },
  {
    id: 6,
    first: 'Ardith',
    last: 'Folds',
    email: 'afolds5@skype.com',
  },
  {
    id: 7,
    first: 'Lilian',
    last: 'Burchatt',
    email: 'lburchatt6@google.it',
  },
  {
    id: 8,
    first: 'Jolene',
    last: 'Willcott',
    email: 'jwillcott7@mail.ru',
  },
  {
    id: 9,
    first: 'Jenine',
    last: 'Roan',
    email: 'jroan8@disqus.com',
  },
  {
    id: 10,
    first: 'Glennie',
    last: 'Klus',
    email: 'gklus9@dell.com',
  },
  {
    id: 11,
    first: 'Irving',
    last: 'Cobleigh',
    email: 'icobleigha@indiatimes.com',
  },
  {
    id: 12,
    first: 'Elvira',
    last: 'Kinsman',
    email: 'ekinsmanb@washingtonpost.com',
  },
  {
    id: 13,
    first: 'Jessalyn',
    last: 'Bohden',
    email: 'jbohdenc@friendfeed.com',
  },
  {
    id: 14,
    first: 'Heloise',
    last: 'Driver',
    email: 'hdriverd@oakley.com',
  },
  {
    id: 15,
    first: 'Caril',
    last: 'Dunkerley',
    email: 'cdunkerleye@who.int',
  },
  {
    id: 16,
    first: 'Paolo',
    last: 'Doumenc',
    email: 'pdoumencf@ycombinator.com',
  },
  {
    id: 17,
    first: 'Annis',
    last: 'Swaffer',
    email: 'aswafferg@abc.net.au',
  },
  {
    id: 18,
    first: 'Harper',
    last: 'Norway',
    email: 'hnorwayh@dagondesign.com',
  },
  {
    id: 19,
    first: 'Adlai',
    last: 'Seide',
    email: 'aseidei@microsoft.com',
  },
  {
    id: 20,
    first: 'Lacey',
    last: 'Bockin',
    email: 'lbockinj@businessinsider.com',
  },
  {
    id: 21,
    first: 'Dagny',
    last: 'Robardley',
    email: 'drobardleyk@virginia.edu',
  },
  {
    id: 22,
    first: 'Batsheva',
    last: 'Prahm',
    email: 'bprahml@huffingtonpost.com',
  },
  {
    id: 23,
    first: 'Doria',
    last: 'Gomery',
    email: 'dgomerym@dell.com',
  },
  {
    id: 24,
    first: 'Robin',
    last: 'Darkins',
    email: 'rdarkinsn@istockphoto.com',
  },
  {
    id: 25,
    first: 'Tomasine',
    last: 'Stratten',
    email: 'tstratteno@ibm.com',
  },
  {
    id: 26,
    first: 'Dawna',
    last: 'Watkiss',
    email: 'dwatkissp@hibu.com',
  },
  {
    id: 27,
    first: 'Gypsy',
    last: 'Hurich',
    email: 'ghurichq@macromedia.com',
  },
  {
    id: 28,
    first: 'Marybeth',
    last: 'Magarrell',
    email: 'mmagarrellr@pen.io',
  },
  {
    id: 29,
    first: 'Edward',
    last: 'Hartright',
    email: 'ehartrights@vk.com',
  },
  {
    id: 30,
    first: 'Audry',
    last: 'Tebbet',
    email: 'atebbett@marriott.com',
  },
  {
    id: 31,
    first: 'Felizio',
    last: 'Lympenie',
    email: 'flympenieu@sciencedaily.com',
  },
  {
    id: 32,
    first: 'Kori',
    last: 'Drescher',
    email: 'kdrescherv@unesco.org',
  },
  {
    id: 33,
    first: 'Lew',
    last: 'Navan',
    email: 'lnavanw@google.ru',
  },
  {
    id: 34,
    first: 'Bennie',
    last: 'Heynel',
    email: 'bheynelx@usatoday.com',
  },
  {
    id: 35,
    first: 'Tania',
    last: 'Michell',
    email: 'tmichelly@infoseek.co.jp',
  },
  {
    id: 36,
    first: 'Fiona',
    last: 'Haithwaite',
    email: 'fhaithwaitez@wordpress.org',
  },
  {
    id: 37,
    first: 'Barclay',
    last: 'Milne',
    email: 'bmilne10@livejournal.com',
  },
];

export default DATA_MOCK;
